create rootf's & SDK from 2018.02.9 buildroot (#10)
---------

Co-authored-by: tiopex <tiopxyz@gmail.com>
Co-authored-by: tiopex <67048640+tiopex@users.noreply.github.com>

diff --git a/package/openvpn/S60openvpn b/package/openvpn/S60openvpn
--- a/package/openvpn/S60openvpn
+++ b/package/openvpn/S60openvpn
@@ -7,19 +7,19 @@
 
 test $DEBIAN_SCRIPT_DEBUG && set -v -x
 
+DAEMON=/usr/sbin/openvpn
 CONFIG_DIR=/etc/openvpn
+test -x $DAEMON || exit 0
 test -d $CONFIG_DIR || exit 0
 
 start_vpn () {
-    printf " $NAME "
-    start-stop-daemon -S -p /var/run/openvpn.$NAME.pid -x /usr/sbin/openvpn -- \
-	      --daemon --writepid /var/run/openvpn.$NAME.pid \
-	      --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+            --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR || printf " FAILED->"
+    printf " $NAME"
 }
 stop_vpn () {
-    printf " $NAME "
-    start-stop-daemon -K -p /var/run/openvpn.$NAME.pid -x /usr/sbin/openvpn
+   kill `cat $PIDFILE` || true
+  rm $PIDFILE
 }
 
 case "$1" in
@@ -50,6 +50,7 @@ stop)
       NAME=`echo $PIDFILE | cut -c18-`
       NAME=${NAME%%.pid}
       stop_vpn
+      printf " $NAME"
     done
   else
     if test -e /var/run/openvpn.$2.pid ; then
@@ -57,6 +58,7 @@ stop)
       NAME=`echo $PIDFILE | cut -c18-`
       NAME=${NAME%%.pid}
       stop_vpn
+      printf " $NAME"
     else
       printf " No such VPN: $2"
     fi
@@ -77,6 +79,8 @@ reload|force-reload)
       printf "(restarted)"
     else
       kill -HUP `cat $PIDFILE` || true
+#    start-stop-daemon --stop --signal HUP --quiet --oknodo \
+#      --exec $DAEMON --pidfile $PIDFILE
     printf " $NAME"
     fi
   done
