firstboot/main: mv logs to /mnt/logs/ &use tmp if needed only
use `mkdir -p` for dir creation to omit silly errors

diff --git a/board/miyoo/rootfs/etc/main b/board/miyoo/rootfs/etc/main
--- a/board/miyoo/rootfs/etc/main
+++ b/board/miyoo/rootfs/etc/main
@@ -8,18 +8,22 @@ export SDL_NOMOUSE=1
 START="${HOME}/autoexec.sh"
 
 LOGS=/dev/null
+LOGS_TEMP=/dev/null
 UMTPR_LOGS=/dev/null
 GMENU2X_LOGS=/dev/null
 
 # check if it's first boot and turn on messages if yes
 if ((test -r "${BOOTDIR}/firstboot") || (test -r "${HOME}/firstboot.completed")); then
 	DEBUG_MSG="yes"
-	LOGS=$(mktemp)
-	UMTPR_LOGS="${HOME}/log_umtpr.txt"
-	GMENU2X_LOGS="${HOME}/log_gmenu2x.txt"
+	LOGS_TEMP=$(mktemp)
+	mkdir -p ${HOME}/logs
+	LOGS="${HOME}/logs/log.txt"
+	UMTPR_LOGS="${HOME}/logs/log_umtpr.txt"
+	GMENU2X_LOGS="${HOME}/logs/log_gmenu2x.txt"
 fi
 
 export LOGS # so that subshells can use this as well
+export LOGS_TEMP
 export GMENU2X_LOGS
 
 if test "x${DEBUG_MSG}" == "xyes"; then
@@ -29,17 +33,22 @@ else
 	echo -e "\e[30m"   # black foreground color
 fi
 
+restore_temp_log_func(){
+	cat ${LOGS_TEMP} >> ${LOGS}
+	LOGS_TEMP=$(mktemp)
+}
+
 # load kernel modules
 
 # load usb gadget
-echo "Loading USB gadget" | tee -a "${LOGS}"
+echo "Loading USB gadget" >> "${LOGS}"
 mount none /sys/kernel/config -t configfs | tee -a "${LOGS}"
-mkdir /sys/kernel/config/usb_gadget/g2 >> "${LOGS}"
-cd /sys/kernel/config/usb_gadget/g2 >> "${LOGS}"
-mkdir configs/c.1 >> "${LOGS}"
-mkdir functions/ffs.mtp >> "${LOGS}"
-mkdir strings/0x409 >> "${LOGS}"
-mkdir configs/c.1/strings/0x409 >> "${LOGS}"
+mkdir -p /sys/kernel/config/usb_gadget/g2 >> "${LOGS}"
+cd /sys/kernel/config/usb_gadget/g2 || echo "Failed to cd into /sys/kernel/config/usb_gadget/g2" >> "${LOGS}"
+mkdir -p configs/c.1 >> "${LOGS}"
+mkdir -p functions/ffs.mtp >> "${LOGS}"
+mkdir -p strings/0x409 >> "${LOGS}"
+mkdir -p configs/c.1/strings/0x409 >> "${LOGS}"
 
 echo 0x0100 > idProduct
 echo 0x1D6B > idVendor
@@ -50,7 +59,7 @@ echo "Miyoo CFW 2.0" > strings/0x409/product
 echo "Conf 1" > configs/c.1/strings/0x409/configuration
 echo 120 > configs/c.1/MaxPower
 ln -s functions/ffs.mtp configs/c.1 | tee -a "${LOGS}"
-mkdir /dev/ffs-mtp >> "${LOGS}"
+mkdir -p /dev/ffs-mtp >> "${LOGS}"
 mount -t functionfs mtp /dev/ffs-mtp | tee -a "${LOGS}"
 umtprd >> "${UMTPR_LOGS}" 2>&1 &
 sleep 1
@@ -67,18 +76,20 @@ BACKLIGHT=$(cat ${HOME}/.backlight.conf)
 
 # TVout scripting backend
 if test -r "${HOME}/tvout"; then
+	echo "Starting TVout video." >> "${LOGS}"
 	echo 0 > /sys/class/backlight/backlight/brightness
 	echo 0 > /sys/class/vtconsole/vtcon1/bind
 	if test $BACKLIGHT -ne 0; then
-		cp ${HOME}/.backlight.conf ${HOME}/.backlight.bak
+		cp ${HOME}/.backlight.conf ${HOME}/.backlight.bak | tee -a "${LOGS}"
 	fi
 	echo 0 > ${HOME}/.backlight.conf
-	modprobe -r $video
+	modprobe -r $video | tee -a "${LOGS}"
 	#TVMODE options.cfg setting 
 	tvmode=$(grep -o TVMODE=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
-	modprobe miyoo-tvout $tvmode
+	echo "Loding TV module miyoo-tvout with args tvmode=${tvmode}" >> "${LOGS}"
+	modprobe miyoo-tvout $tvmode | tee -a "${LOGS}"
 	echo 1 > /sys/class/vtconsole/vtcon1/bind
-	modprobe -r $video
+	modprobe -r $video | tee -a "${LOGS}"
 else
 	if ((test -r "${HOME}/.backlight.bak")); then
 		mv ${HOME}/.backlight.bak ${HOME}/.backlight.conf
@@ -87,9 +98,9 @@ else
 	if (!(test -r "${BOOTDIR}/modules.custom.sh") || !(grep -q MODULES_CUSTOM\=\1 "${HOME}/options.cfg")); then
 		# Load video module read from uEnv.txt & defined by variant in console.cfg
 		#FLIP & INVERT options.cfg setting
-		echo "Loding video module with args" >> "${LOGS}"
 		flip=$(grep -o FLIP=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
 		invert=$(grep -o INVERT=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
+		echo "Loding video module ${video} with args flip=${flip} invert=${invert}" >> "${LOGS}"
 		modprobe $video $flip $invert | tee -a "${LOGS}"
 	else
 		echo "Loding custom modules." >> "${LOGS}"
@@ -107,35 +118,36 @@ fi
 if !(grep -q FS_CHECK\=\0 "${HOME}/options.cfg"); then
 ##Check if BOOT (FAT16) is flagged as "dirty", and if so unmount, repair, remount
 	if dmesg | grep "mmcblk0p1" > /dev/null;  then
-		echo -e "\e[31mDirty sectors detected.\e[0m"
-		echo -e "\e[32mChecking&Repairing FAT16 BOOT partition...\e[0m"
-		umount /dev/mmcblk0p1
-		fsck.vfat -y /dev/mmcblk0p1 > /dev/null; 
-		mount /dev/mmcblk0p1 "${BOOTDIR}" -t vfat -o ro,exec,utf8
-		echo -e "\e[32mCheck complete.\e[0m"
+		echo -e "\e[31mDirty sectors detected.\e[0m" | tee -a "${LOGS}"
+		echo -e "\e[32mChecking&Repairing FAT16 BOOT partition...\e[0m" | tee -a "${LOGS}"
+		umount /dev/mmcblk0p1 | tee -a "${LOGS}"
+		fsck.vfat -y /dev/mmcblk0p1 >> "${LOGS}"
+		mount /dev/mmcblk0p1 "${BOOTDIR}" -t vfat -o ro,exec,utf8 | tee -a "${LOGS}"
+		echo -e "\e[32mCheck complete.\e[0m" | tee -a "${LOGS}"
 	fi
 ##Check if MAIN (EXT4) is flagged as "dirty", and if so unmount, repair, remount
 	if dmesg | grep "EXT4-fs (mmcblk0p4): warning: mounting fs with errors, running e2fsck is recommended" > /dev/null;  then
-		echo -e "\e[31mUnclean shutdown detected.\e[0m"
-		echo -e "\e[32mChecking MAIN(EXT4) partition...\e[0m"
-		umount /dev/mmcblk0p4
-		e2fsck -y /dev/mmcblk0p4 > /dev/null; 
-		mount /dev/mmcblk0p4 "${HOME}" -o rw,sync,exec
+		echo -e "\e[31mUnclean shutdown detected.\e[0m" | tee -a "${LOGS}"
+		echo -e "\e[32mChecking MAIN(EXT4) partition...\e[0m" | tee -a "${LOGS}"
+		umount /dev/mmcblk0p4 | tee -a "${LOGS_TEMP}"
+		e2fsck -y /dev/mmcblk0p4 >> "${LOGS_TEMP}";
+		mount /dev/mmcblk0p4 "${HOME}" -o rw,sync,exec | tee -a "${LOGS_TEMP}"
+		restore_temp_log_func
 	fi
 ##Check if ROMS (EXT4 or FAT32) is flagged as "dirty", and if so unmount, repair, remount
 	if dmesg | grep "EXT4-fs (mmcblk0p5): warning: mounting fs with errors, running e2fsck is recommended" > /dev/null;  then
-		echo -e "\e[31mUnclean shutdown detected.\e[0m"
-		echo -e "\e[32mChecking ROMS(EXT4) partition...\e[0m"
-		umount /dev/mmcblk0p5
-		e2fsck -y /dev/mmcblk0p5 > /dev/null; 
-		mount /dev/mmcblk0p5 "${ROMS}" -o rw,noatime
+		echo -e "\e[31mUnclean shutdown detected.\e[0m" | tee -a "${LOGS}"
+		echo -e "\e[32mChecking ROMS(EXT4) partition...\e[0m" | tee -a "${LOGS}"
+		umount /dev/mmcblk0p5 | tee -a "${LOGS}"
+		e2fsck -y /dev/mmcblk0p5 >> "${LOGS}"; 
+		mount /dev/mmcblk0p5 "${ROMS}" -o rw,noatime | tee -a "${LOGS}"
 	elif dmesg | grep "FAT-fs (mmcblk0p5): Volume was not properly unmounted. Some data may be corrupt. Please run fsck." > /dev/null;  then
-		echo -e "\e[31mDirty sectors detected.\e[0m"
-		echo -e "\e[32mChecking&Repairing ROMS(FAT32) partition...\e[0m"
-		umount /dev/mmcblk0p5
-		fsck.vfat -y /dev/mmcblk0p5 > /dev/null; 
-		mount /dev/mmcblk0p5 "${ROMS}" -t vfat -o rw,utf8
-		echo -e "\e[32mCheck complete.\e[0m"
+		echo -e "\e[31mDirty sectors detected.\e[0m" | tee -a "${LOGS}"
+		echo -e "\e[32mChecking&Repairing ROMS(FAT32) partition...\e[0m" | tee -a "${LOGS}"
+		umount /dev/mmcblk0p5 | tee -a "${LOGS}"
+		fsck.vfat -y /dev/mmcblk0p5 >> "${LOGS}"
+		mount /dev/mmcblk0p5 "${ROMS}" -t vfat -o rw,utf8 | tee -a "${LOGS}"
+		echo -e "\e[32mCheck complete.\e[0m" | tee -a "${LOGS}"
 	fi
 fi
 
@@ -163,15 +175,14 @@ if (!(grep -q BOOT_LOGO\=\0 "${HOME}/options.cfg")); then
 	${BOOTLOGO} >> "${LOGS}" 2>&1
 fi
 
-# can't unmount boot because 'daemon' runs from it - but it's mounted read-only
-#  so it's fine
+# we could unmount /boot here but since it's read-only it doesn't hurt to leave it running
 ## umount /dev/mmcblk0p1
 
 # Writes dmesg after firstboot procedure or if DEBUG_MSG=yes
 if test "x${DEBUG_MSG}" == "xyes"; then
 	sleep 1
-	dmesg > ${HOME}/dmesg.txt
-	mv ${LOGS} ${HOME}/log.txt
+	dmesg > ${HOME}/logs/dmesg.txt
+	restore_temp_log_func
 fi
 
 while [ 1 ]
