output also stderr to logs
also refactor a bit gmenu2x loop

diff --git a/board/miyoo/rootfs/etc/main b/board/miyoo/rootfs/etc/main
--- a/board/miyoo/rootfs/etc/main
+++ b/board/miyoo/rootfs/etc/main
@@ -42,13 +42,13 @@ restore_temp_log_func(){
 
 # load usb gadget
 echo "Loading USB gadget" >> "${LOGS}"
-mount none /sys/kernel/config -t configfs | tee -a "${LOGS}"
-mkdir -p /sys/kernel/config/usb_gadget/g2 >> "${LOGS}"
-cd /sys/kernel/config/usb_gadget/g2 || echo "Failed to cd into /sys/kernel/config/usb_gadget/g2" >> "${LOGS}"
-mkdir -p configs/c.1 >> "${LOGS}"
-mkdir -p functions/ffs.mtp >> "${LOGS}"
-mkdir -p strings/0x409 >> "${LOGS}"
-mkdir -p configs/c.1/strings/0x409 >> "${LOGS}"
+mount none /sys/kernel/config -t configfs 2>&1 | tee -a "${LOGS}"
+mkdir -p /sys/kernel/config/usb_gadget/g2 >> "${LOGS}" 2>&1
+cd /sys/kernel/config/usb_gadget/g2 || echo "Failed to cd into /sys/kernel/config/usb_gadget/g2" >> "${LOGS}" 2>&1
+mkdir -p configs/c.1 >> "${LOGS}" 2>&1
+mkdir -p functions/ffs.mtp >> "${LOGS}" 2>&1
+mkdir -p strings/0x409 >> "${LOGS}" 2>&1
+mkdir -p configs/c.1/strings/0x409 >> "${LOGS}" 2>&1
 
 echo 0x0100 > idProduct
 echo 0x1D6B > idVendor
@@ -58,9 +58,9 @@ echo "Miyoo CFW 2.0" > strings/0x409/product
 
 echo "Conf 1" > configs/c.1/strings/0x409/configuration
 echo 120 > configs/c.1/MaxPower
-ln -s functions/ffs.mtp configs/c.1 | tee -a "${LOGS}"
-mkdir -p /dev/ffs-mtp >> "${LOGS}"
-mount -t functionfs mtp /dev/ffs-mtp | tee -a "${LOGS}"
+ln -s functions/ffs.mtp configs/c.1 2>&1 | tee -a "${LOGS}"
+mkdir -p /dev/ffs-mtp >> "${LOGS}" 2>&1
+mount -t functionfs mtp /dev/ffs-mtp 2>&1 | tee -a "${LOGS}"
 umtprd >> "${UMTPR_LOGS}" 2>&1 &
 sleep 1
 ls /sys/class/udc/ > /sys/kernel/config/usb_gadget/g2/UDC
@@ -80,16 +80,16 @@ if test -r "${HOME}/tvout"; then
 	echo 0 > /sys/class/backlight/backlight/brightness
 	echo 0 > /sys/class/vtconsole/vtcon1/bind
 	if test $BACKLIGHT -ne 0; then
-		cp ${HOME}/.backlight.conf ${HOME}/.backlight.bak | tee -a "${LOGS}"
+		cp ${HOME}/.backlight.conf ${HOME}/.backlight.bak 2>&1 | tee -a "${LOGS}"
 	fi
 	echo 0 > ${HOME}/.backlight.conf
-	modprobe -r $video | tee -a "${LOGS}"
+	modprobe -r $video 2>&1 | tee -a "${LOGS}"
 	#TVMODE options.cfg setting 
 	tvmode=$(grep -o TVMODE=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
 	echo "Loding TV module miyoo-tvout with args tvmode=${tvmode}" >> "${LOGS}"
-	modprobe miyoo-tvout $tvmode | tee -a "${LOGS}"
+	modprobe miyoo-tvout $tvmode 2>&1 | tee -a "${LOGS}"
 	echo 1 > /sys/class/vtconsole/vtcon1/bind
-	modprobe -r $video | tee -a "${LOGS}"
+	modprobe -r $video 2>&1 | tee -a "${LOGS}"
 else
 	if ((test -r "${HOME}/.backlight.bak")); then
 		mv ${HOME}/.backlight.bak ${HOME}/.backlight.conf
@@ -101,7 +101,7 @@ else
 		flip=$(grep -o FLIP=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
 		invert=$(grep -o INVERT=[0-1] "${HOME}/options.cfg" | tr '[:upper:]' '[:lower:]')
 		echo "Loding video module ${video} with args flip=${flip} invert=${invert}" >> "${LOGS}"
-		modprobe $video $flip $invert | tee -a "${LOGS}"
+		modprobe $video $flip $invert 2>&1 | tee -a "${LOGS}"
 	else
 		echo "Loding custom modules." >> "${LOGS}"
 		(cd "${BOOTDIR}" && sh modules.custom.sh ) >> "${LOGS}" 2>&1
@@ -120,33 +120,33 @@ if !(grep -q FS_CHECK\=\0 "${HOME}/options.cfg"); then
 	if dmesg | grep "mmcblk0p1" > /dev/null;  then
 		echo -e "\e[31mDirty sectors detected.\e[0m" | tee -a "${LOGS}"
 		echo -e "\e[32mChecking&Repairing FAT16 BOOT partition...\e[0m" | tee -a "${LOGS}"
-		umount /dev/mmcblk0p1 | tee -a "${LOGS}"
-		fsck.vfat -y /dev/mmcblk0p1 >> "${LOGS}"
-		mount /dev/mmcblk0p1 "${BOOTDIR}" -t vfat -o ro,exec,utf8 | tee -a "${LOGS}"
+		umount /dev/mmcblk0p1 2>&1 | tee -a "${LOGS}"
+		fsck.vfat -y /dev/mmcblk0p1 >> "${LOGS}" 2>&1
+		mount /dev/mmcblk0p1 "${BOOTDIR}" -t vfat -o ro,exec,utf8 2>&1 | tee -a "${LOGS}"
 		echo -e "\e[32mCheck complete.\e[0m" | tee -a "${LOGS}"
 	fi
 ##Check if MAIN (EXT4) is flagged as "dirty", and if so unmount, repair, remount
 	if dmesg | grep "EXT4-fs (mmcblk0p4): warning: mounting fs with errors, running e2fsck is recommended" > /dev/null;  then
 		echo -e "\e[31mUnclean shutdown detected.\e[0m" | tee -a "${LOGS}"
 		echo -e "\e[32mChecking MAIN(EXT4) partition...\e[0m" | tee -a "${LOGS}"
-		umount /dev/mmcblk0p4 | tee -a "${LOGS_TEMP}"
+		umount /dev/mmcblk0p4 2>&1 | tee -a "${LOGS_TEMP}"
 		e2fsck -y /dev/mmcblk0p4 >> "${LOGS_TEMP}";
-		mount /dev/mmcblk0p4 "${HOME}" -o rw,sync,exec | tee -a "${LOGS_TEMP}"
+		mount /dev/mmcblk0p4 "${HOME}" -o rw,sync,exec 2>&1 | tee -a "${LOGS_TEMP}"
 		restore_temp_log_func
 	fi
 ##Check if ROMS (EXT4 or FAT32) is flagged as "dirty", and if so unmount, repair, remount
 	if dmesg | grep "EXT4-fs (mmcblk0p5): warning: mounting fs with errors, running e2fsck is recommended" > /dev/null;  then
 		echo -e "\e[31mUnclean shutdown detected.\e[0m" | tee -a "${LOGS}"
 		echo -e "\e[32mChecking ROMS(EXT4) partition...\e[0m" | tee -a "${LOGS}"
-		umount /dev/mmcblk0p5 | tee -a "${LOGS}"
-		e2fsck -y /dev/mmcblk0p5 >> "${LOGS}"; 
-		mount /dev/mmcblk0p5 "${ROMS}" -o rw,noatime | tee -a "${LOGS}"
+		umount /dev/mmcblk0p5 2>&1 | tee -a "${LOGS}"
+		e2fsck -y /dev/mmcblk0p5 >> "${LOGS}" 2>&1; 
+		mount /dev/mmcblk0p5 "${ROMS}" -o rw,noatime 2>&1 | tee -a "${LOGS}"
 	elif dmesg | grep "FAT-fs (mmcblk0p5): Volume was not properly unmounted. Some data may be corrupt. Please run fsck." > /dev/null;  then
 		echo -e "\e[31mDirty sectors detected.\e[0m" | tee -a "${LOGS}"
 		echo -e "\e[32mChecking&Repairing ROMS(FAT32) partition...\e[0m" | tee -a "${LOGS}"
-		umount /dev/mmcblk0p5 | tee -a "${LOGS}"
-		fsck.vfat -y /dev/mmcblk0p5 >> "${LOGS}"
-		mount /dev/mmcblk0p5 "${ROMS}" -t vfat -o rw,utf8 | tee -a "${LOGS}"
+		umount /dev/mmcblk0p5 2>&1 | tee -a "${LOGS}"
+		fsck.vfat -y /dev/mmcblk0p5 >> "${LOGS}" 2>&1
+		mount /dev/mmcblk0p5 "${ROMS}" -t vfat -o rw,utf8 2>&1 | tee -a "${LOGS}"
 		echo -e "\e[32mCheck complete.\e[0m" | tee -a "${LOGS}"
 	fi
 fi
@@ -191,11 +191,11 @@ do
 		source "${START}"
 	else
 		echo "Starting GMenu2x" >> "${LOGS}"
-		cd "${HOME}"/gmenu2x || exit;
+		cd "${HOME}"/gmenu2x || { echo "Failed to cd into ${HOME}/gmenu2x" >> "${LOGS}" ; exit; }
 		if (!(grep -q DEBUG\=\0 "${HOME}/options.cfg")); then
-			gdb -ex="set confirm off" -ex=run -ex="bt full" -ex=q ./gmenu2x-debug >> "${GMENU2X_LOGS}"
+			gdb -ex="set confirm off" -ex=run -ex="bt full" -ex=q ./gmenu2x-debug >> "${GMENU2X_LOGS}" 2>&1
 		else
-			./gmenu2x >> "${GMENU2X_LOGS}" 2>&1;
+			./gmenu2x >> "${GMENU2X_LOGS}" 2>&1
 		fi
 	fi
 	clear
