BOARD: allow for switching FS for ROMS
Update firstboot

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -518,41 +518,42 @@ P4_SIZE=$(cat "/sys/block/mmcblk0/mmcblk0p4/size") # MAIN
 P5_SIZE=$(cat "/sys/block/mmcblk0/mmcblk0p5/size") # ROMS
 SD_SIZE_IN_MiB=$((SD_SIZE * 512 / 1024 / 1024))
 SD_SIZE_IN_GiB=$((SD_SIZE * 512 / 1024 / 1024 / 1024))
-BOOT_SIZE=$(((1016+1) * 1024 / 512)) #bootloader partition=1016K (see `genimage` script in buildroot)
-## boot_size calculated to 512 byte sector size blocks, adding +1K as a safety measure for roundups (at fatresize we use KibiBits)
+BOOT_SIZE=$(((1016+1 - 1000 + 1024) * 1024 / 512)) #bootloader partition=1016K (see `genimage` script in buildroot)
+												   ## boot_size calculated to 512 byte sector size blocks, adding +1K as a safety measure for roundups (at fatresize we use KibiBits)
+												   ## adding 1M (1024) for GPT align offset
 
 #Calculate unallocated left space to expand ROMS partition:
 SD_MAX_UNALL_SIZE="$((${SD_SIZE} - (${P1_SIZE} + ${P2_SIZE} + ${P3_SIZE} + ${P4_SIZE} + ${P5_SIZE}) - $BOOT_SIZE))"
 SD_MAX_UNALL_SIZE_IN_MiB=$((SD_MAX_UNALL_SIZE * 512 / 1024 / 1024))
 SD_MAX_UNALL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_UNALL_SIZE} * 512 / 1024 / 1024 / 1024" | bc)
 
-#Calculate available space for 4'th partition (ROMS):
-SD_MAX_AVAIL_SIZE="$((${SD_SIZE} - (${P1_SIZE} + ${P2_SIZE} + ${P3_SIZE}) - $BOOT_SIZE))"
+#Calculate available space for 5'th partition (ROMS):
+SD_MAX_AVAIL_SIZE="$((${SD_SIZE} - (${P1_SIZE} + ${P2_SIZE} + ${P3_SIZE} + ${P4_SIZE}) - $BOOT_SIZE))"
 SD_MAX_AVAIL_SIZE_IN_KiB=$((SD_MAX_AVAIL_SIZE * 512 / 1024))
 
 # Change_MAIN_FileSystem-prompt for the p4 partition if requested
 CHANGE_FS_P4=false
 if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label ${P4_FS_TYPE}\(default\) --cancel-label EXT4 --title "   Change FileSystem" \
    --colors --pause "\n\n\Z5Change default FileSystem of MAIN?\Zn\n\n   BTRFS - safe & reliable\Zn\n\n   EXT4 - fast & optimal\Zn\n\n   Select an option & press START
-   \n\n             \ZbWARNING:\Zn\n       After 10s changes\n   to MAIN partition won't be possible." 15 60 10); then
+   \n\n             \ZbWARNING:\Zn\n       After 2min changes\n   to MAIN partition won't be possible." 15 60 120); then
 	
 	echo "Selected ${P4_FS_TYPE} for MAIN partition, continuing with default setup." | tee -a ${LOG}
 	sleep 2
 else
 	P4_FS_TYPE="EXT4"
 	echo -en "\n\nConverting the MAIN partition filesystem to ${P4_FS_TYPE} type.\n\n" | tee -a ${LOG}
-	echo -en "This can take a few minutes...be patient!"
+	echo -en "This can take a few minutes, be patient!"
+	sleep 3
 	mkdir /roms/backup
-	cp -a "${HOME}" /roms/backup
+	cp -v -a "${HOME}" /roms/backup
 	umount /dev/mmcblk0p4 | tee -a ${LOG}
-	# P4_START_POINT=` parted --script /dev/mmcblk0 unit MB print | grep '4' | tail -n1 | awk '{print $2}'`
-	# P4_END_POINT=` parted --script /dev/mmcblk0 unit MB print | grep '4' | tail -n1 | awk '{print $3}'`
-	# parted -a optimal /dev/mmcblk0 --script rm '4'  | tee -a ${LOG}
-	# parted -a optimal /dev/mmcblk0 --script mkpart main $P4_START_POINT $P4_END_POINT  | tee -a ${LOG}
-	# partx -u /dev/mmcblk0  | tee -a ${LOG}
-	mkfs.ext4 -q -F /dev/mmcblk0p4
+	clear
+	echo -en "\n\n"
+	mkfs.ext4 -q -F /dev/mmcblk0p4 | tee -a ${LOG}
+	sleep 2
+	e2fsck -y /dev/mmcblk0p4 | tee -a ${LOG}
 	mount /dev/mmcblk0p4 "${HOME}" -o rw,sync | tee -a ${LOG}
-	cp -a /roms/backup/"${HOME}" /
+	cp -v -a /roms/backup/"${HOME}" /
 	rm -r /roms/backup
 	CHANGE_FS_P4=true
 fi
@@ -563,11 +564,44 @@ if ( $CHANGE_FS_P4 ); then
 	mount -o remount,ro / /
 fi
 
+# Change_ROMS_FileSystem-prompt for the p5 partition if requested
+CHANGE_FS_P5=false
+if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label ${P5_FS_TYPE}\(default\) --cancel-label FAT32 --title "   Change FileSystem" \
+   --colors --pause "\n\n\Z5Change default FileSystem for ROMS?\Zn\n\nEXT4 - fast write/read & UNIX compliant\Zn\n\nFAT32 - slow on-device write but Windows compatbile\Zn\n\n   Select an option & press START
+   \n\n             \ZbWARNING:\Zn\n       After 30min changes\n   to ROMS partition won't be possible." 15 60 1800); then
+	
+	echo "Selected ${P5_FS_TYPE} for ROMS partition, continuing with default setup." | tee -a ${LOG}
+	sleep 2
+else
+	P5_FS_TYPE="FAT32"
+	echo -en "\n\nConverting the ROMS partition filesystem to ${P5_FS_TYPE} type.\n\n" | tee -a ${LOG}
+	echo -en "This can take A LONG TIME, be patient!"
+	sleep 3
+	mkdir "${HOME}"/backup
+	cp -v -a /roms "${HOME}"/backup
+	umount /dev/mmcblk0p5 | tee -a ${LOG}
+	clear
+	echo -en "\n\n"
+	mkfs.vfat -n ROMS -v -F32 /dev/mmcblk0p5 | tee -a ${LOG}
+	sleep 2
+	fsck.fat -y /dev/mmcblk0p4 | tee -a ${LOG}
+	mount /dev/mmcblk0p5 /roms -t vfat -o rw,sync,utf8 | tee -a ${LOG}
+	cp -v -a "${HOME}"/backup/roms /
+	rm -r "${HOME}"/backup
+	CHANGE_FS_P5=true
+fi
+## Correct inittab for new p5 filesystem type
+if ( $CHANGE_FS_P5 ); then
+	mount -o remount,rw / /
+	sed -i "s|\(::sysinit:/bin/mount /dev/mmcblk0p5\).*|\1 /roms -t vfat -o rw,sync,utf8|" /etc/inittab
+	mount -o remount,ro / /
+fi
+
 # Expand_ROMS_Partition-prompt for the p5 (ROMS) partition if requested
 RESIZE_COMMENCED=false
 if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YES --cancel-label NO --title "   AUTO-RESIZE" \
    --colors --pause "\n\n       \Z5Expand ROMS partition?\Zn\n\n   Select an option & press START
-   \n\n             \ZbWARNING:\Zn\n       After 10s auto-resize\n   of ${P5_FS_TYPE} partition will begin." 15 60 10); then
+   \n\n             \ZbWARNING:\Zn\n       After 30min auto-resize\n   of ${P5_FS_TYPE} partition will begin." 15 60 1800); then
 	clear
 	SD_MAX_AVAIL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} / 1024 / 1024" | bc) #only to inform user about end point for resize
 	SD_MAX_AVAIL_SIZE_IN_GB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} * 1024 / 1000 / 1000 / 1000" | bc)
@@ -582,20 +616,45 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 		sleep 1.5
 		RESIZE_ABORT=true
 	fi
+	if test "${P5_FS_TYPE}" == "FAT32" ; then
+		if test "$SD_SIZE_IN_GiB" -gt 128; then
+			if (dialog --clear --stdout --ok-label NO --cancel-label YES --title "   \Zb\Z1WARNING!\Zn" \
+			--colors --pause "\nYour SD card exceeds max. size for auto-resizing! 
+			\n\nWe could however expand it to 118GB. \n\n           \ZuDo you AGREE?\Zn
+			\n\n\ZbINFO: For microSD >128GB big we\n      recommend to use your PC!\Zn" 0 0 30 || test $? -eq 255); then
+				dialog --clear --colors --timeout 2 --msgbox " FAT resizing \ZuABORTED!\Zn" 5 27
+				clear
+				RESIZE_ABORT=true
+			else
+				SD_MAX_AVAIL_SIZE_IN_KiB=123731968
+			fi
+		fi
+	fi
 	if ! $RESIZE_ABORT; then
 		echo "The full size of your SD is ${SD_SIZE_IN_MiB}MB large" | tee -a ${LOG}
 		echo "Unallocated space available for resizing equals ${SD_MAX_UNALL_SIZE_IN_GiB}GB," | tee -a ${LOG}
 		echo "and more precisely it's ${SD_MAX_UNALL_SIZE_IN_MiB}MB big" | tee -a ${LOG}
 		echo "Resizing the ROMS (${P5_FS_TYPE}) partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
-		echo "This can take a few minutes seconds." | tee -a ${LOG}
 		umount /dev/mmcblk0p5 | tee -a ${LOG}
-		P5_START_POINT=` parted --script /dev/mmcblk0 unit MB print | grep '5' | tail -n1 | awk '{print $2}'`
-		parted -a optimal /dev/mmcblk0 --script rm '5'  | tee -a ${LOG}
-		parted -a optimal /dev/mmcblk0 --script mkpart roms $P5_START_POINT 100%  | tee -a ${LOG}
-		partx -u /dev/mmcblk0  | tee -a ${LOG}
-		mount /dev/mmcblk0p5 /roms | tee -a ${LOG}
-		resize2fs /dev/mmcblk0p5 | tee -a ${LOG}
-		partprobe
+		if test "${P5_FS_TYPE}" == "FAT32"; then
+			echo "This can take a minute, so be patient!" | tee -a ${LOG}
+			#TODO: fix outputting logs from fatresize stdout
+			fatresize --size="${SD_MAX_AVAIL_SIZE_IN_KiB}"ki -v -p /dev/mmcblk0p5 -n5 | tee -a ${LOG}
+			fsck.fat -y /dev/mmcblk0p5 | tee -a ${LOG}
+			#echo -n -e \\xEB\\x58\\x90 > /dev/mmcblk0p4
+			sync
+			mount -t vfat -o rw,sync,utf8 /dev/mmcblk0p5 /roms | tee -a ${LOG}
+		else
+			echo "This can take a few seconds." | tee -a ${LOG}
+			P5_START_POINT=` parted --script /dev/mmcblk0 unit MB print | grep '5' | tail -n1 | awk '{print $2}'`
+			parted -a optimal /dev/mmcblk0 --script rm '5'  | tee -a ${LOG}
+			parted -a optimal /dev/mmcblk0 --script mkpart roms $P5_START_POINT 100%  | tee -a ${LOG}
+			partx -u /dev/mmcblk0  | tee -a ${LOG}
+			resize2fs /dev/mmcblk0p5 | tee -a ${LOG}
+			e2fsck -y /dev/mmcblk0p5 | tee -a ${LOG}
+			mount /dev/mmcblk0p5 /roms | tee -a ${LOG}
+			partprobe
+		fi
 		RESIZE_COMMENCED=true
 	else
 		echo "ROMS partition resizing was aborted!" | tee -a ${LOG}
