firsboot: FAT32 is in fact vfat type

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -608,12 +608,16 @@ else
 	echo -en "\e[32mThis can take a few minutes, be patient!\e[0m"
 	sleep 3
 	mkdir "${ROMS}"/backup 2>&1 | tee -a ${LOG}
-	rsync -a --info=nonreg0 --info=progress2 "${HOME}" "${ROMS}"/backup
+	if test "${P5_FS_TYPE}" == "VFAT"; then
+		rsync -rvt --modify-window=1 --exclude "lost+found" --info=nonreg0 --info=progress2 "${HOME}" "${ROMS}"/backup
+	else
+		rsync -a --info=nonreg0 --info=progress2 "${HOME}" "${ROMS}"/backup
+	fi
 	echo $? > $TEMP && EXIT_CODE=$(cat $TEMP)
 	if test $EXIT_CODE -eq 0; then
 		echo "Archiving ${HOME} partition successful" | tee -a ${LOG_TEMP}
 	else
-		echo -en "\033[0;31mArchiving ${HOME} to ${ROMS}/backup failed with rsync exit code ${EXIT_CODE}\033[0m" | tee -a ${LOG_TEMP}
+		echo -en "\033[0;31mArchiving ${HOME} to ${ROMS}/backup failed with rsync exit code ${EXIT_CODE}\033[0m\n" | tee -a ${LOG_TEMP}
 	fi
 	sleep 2
 	umount /dev/mmcblk0p4 2>&1 | tee -a ${LOG_TEMP}
@@ -662,15 +666,15 @@ echo "Change ${P5_LABEL} FileSystem procedure" >> ${LOG}
 CHANGE_FS_P5=false
 test "${P5_FS_TYPE}" == "EXT4"\
  && P5_FS_TYPE_EXTRA="BTRFS"\
- && P5_FS_TYPE_EXTRA2="FAT32"
+ && P5_FS_TYPE_EXTRA2="VFAT"
 test "${P5_FS_TYPE}" == "BTRFS"\
  && P5_FS_TYPE_EXTRA="EXT4"\
- && P5_FS_TYPE_EXTRA2="FAT32"
-test "${P5_FS_TYPE}" == "FAT32"\
+ && P5_FS_TYPE_EXTRA2="VFAT"
+test "${P5_FS_TYPE}" == "VFAT"\
  && P5_FS_TYPE_EXTRA="BTRFS"\
  && P5_FS_TYPE_EXTRA2="EXT4"
 dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label "${P5_FS_TYPE}(def.)" --cancel-label "${P5_FS_TYPE_EXTRA}" --extra-button --extra-label "${P5_FS_TYPE_EXTRA2}" --title "   Change FileSystem" \
-   --colors --pause "\n\n\Z5Change default FileSystem for ${P5_LABEL}?\Zn\n\nEXT4 - fast write/read & UNIX compliant\Zn\n\nBTRFS - slow read but poweroff safe, UNIX compliant\Zn\n\nFAT32 - slow on-device write but Windows compatbile\Zn\n\n   Select an option & press START
+   --colors --pause "\n\n\Z5Change default FileSystem for ${P5_LABEL}?\Zn\n\nEXT4 - fast write/read & UNIX compliant\Zn\n\nBTRFS - slow read but poweroff safe, UNIX compliant\Zn\n\nVFAT(32) - slow on-device write but Windows compatible\Zn\n\n   Select an option & press START
    \n\n             \ZbWARNING:\Zn\n After 30min changes to ${P5_LABEL}\n partition won't be possible." 25 60 1800
 	echo $? > $TEMP
 	## Read the user's first choice from the tmp file
@@ -707,7 +711,7 @@ if $CHANGE_FS_P5; then
 	done
 	clear
 	echo -en "\n\n"
-	if test "${P5_FS_TYPE}" == "FAT32"; then
+	if test "${P5_FS_TYPE}" == "VFAT"; then
 		mkfs.vfat -n ${P5_LABEL} -v -F32 /dev/mmcblk0p5 2>&1 | tee -a ${LOG}
 		sleep 2
 		fsck.fat -y /dev/mmcblk0p5 2>&1 | tee -a ${LOG}
@@ -745,7 +749,7 @@ if $CHANGE_FS_P5; then
 	while (pgrep "mount"); do
 		sleep 1
 	done
-	if test "${P5_FS_TYPE}" == "FAT32"; then
+	if test "${P5_FS_TYPE}" == "VFAT"; then
 		sed -i "s|\(::sysinit:/bin/mount /dev/mmcblk0p5\).*|\1 "${ROMS}" -t vfat -o rw,utf8|" /etc/inittab
 	elif test "${P5_FS_TYPE}" == "BTRFS"; then
 		sed -i "s|\(::sysinit:/bin/mount /dev/mmcblk0p5\).*|\1 "${ROMS}" -o commit=5,flushoncommit,noatime,nodiratime|" /etc/inittab
@@ -776,7 +780,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 		sleep 1.5
 		RESIZE_ABORT=true
 	fi
-	if test "${P5_FS_TYPE}" == "FAT32" ; then
+	if test "${P5_FS_TYPE}" == "VFAT" ; then
 		if test "$SD_SIZE_IN_GiB" -gt 128; then
 			if (dialog --clear --stdout --ok-label NO --cancel-label YES --title "   \Zb\Z1WARNING!\Zn" \
 			--colors --pause "\nYour SD card exceeds max. size for auto-resizing! 
@@ -792,7 +796,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 			fi
 		fi
 	fi
-	if !(test "${P5_FS_TYPE}" == "FAT32" || test "${P5_FS_TYPE}" == "BTRFS" || test "${P5_FS_TYPE}" == "EXT4"); then
+	if !(test "${P5_FS_TYPE}" == "VFAT" || test "${P5_FS_TYPE}" == "BTRFS" || test "${P5_FS_TYPE}" == "EXT4"); then
 		echo "ERROR: I couldn't recognize FSTYPE for ${ROMS} partition, resizing ABORTED!" | tee -a ${LOG}
 		RESIZE_ABORT=true
 	fi
@@ -804,7 +808,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 		echo "and more precisely it's ${SD_MAX_UNALL_SIZE_IN_MiB}MB big" | tee -a ${LOG}
 		echo "Resizing the ${P5_LABEL} (${P5_FS_TYPE}) partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
 		umount /dev/mmcblk0p5 2>&1 | tee -a ${LOG}
-		if test "${P5_FS_TYPE}" == "FAT32"; then
+		if test "${P5_FS_TYPE}" == "VFAT"; then
 			echo -en "\e[32mThis can take a few minutes, be patient!\e[0m"
 			#TODO: fix outputting logs from fatresize stdout
 			fatresize --size="${SD_MAX_AVAIL_SIZE_IN_KiB}"ki -v -p /dev/mmcblk0p5 -n5 2>&1 | tee -a ${LOG}
@@ -838,7 +842,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 		sleep 2
 	fi
 fi
-if ! $RESIZE_COMMENCED && test "${P5_FS_TYPE}" == "FAT32" ; then
+if ! $RESIZE_COMMENCED && test "${P5_FS_TYPE}" == "VFAT" ; then
 	sgdisk --typecode=5:0700 /dev/mmcblk0  2>&1 | tee -a ${LOG} # Microsoft basic data - partition type
 	partprobe 2>&1 | tee -a ${LOG}
 	echo "Executed partprobe to correct partition table." >> ${LOG}
