[BOARD] add functions to handle ERROR/ESC exit status
also add: console_unknown_func() and default_console_func()

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -127,34 +127,48 @@ done
 if ! $FOUND_CONSOLE && ! $FOUND_CONSOLE_AUTO; then
 	if (grep "DETECTED_VERSION=V90/Q90/Q20/PocketGo ST7789S controller" "${MOUNTDIR}/uEnv.txt"); then
 		# Test_Video if proper miyoo video's version driver was loaded:
-		dialog --defaultno --ok-label NO --cancel-label "Flipped!" --extra-button --extra-label YES --stdout --title   "   Test Video" \
-		--colors --pause "\n\n   \ZuCan you see this message?\Zn\n\nSelect an option & press START" 12 34 10
+		test_video_func(){
+			dialog --defaultno --ok-label NO --cancel-label "Flipped!" --extra-button --extra-label YES --stdout --title   "   Test Video" \
+			--colors --pause "\n\n   \ZuCan you see this message?\Zn\n\nSelect an option&press START/Y/B" 12 36 10
 
-		echo $? > $TEMP
-		## Read the user's first choice from the tmp file
-		CHOICE_FIRST=$(cat $TEMP)
+			echo $? > $TEMP
+			## Read the user's first choice from the tmp file
+			CHOICE_FIRST=$(cat $TEMP)
 
-		# "YES" choice for Test_Video msgbox DIALOG_EXTRA exit code
-		if test $CHOICE_FIRST -eq 3; then
-			# Correct variant for st7789s (non forced)
-			echo "CONSOLE_VARIANT=st7789s" > ${MOUNTDIR}/console.cfg	
-		# "Flipped!" choice for Test_Video msgbox DIALOG_CANCEL exit code
-		elif test $CHOICE_FIRST -eq 1; then
-			# Correct variant for bittboy3.5 (non forced)
-			echo "CONSOLE_VARIANT=bittboy3" > ${MOUNTDIR}/console.cfg
-			sync
-			sleep 0.1
-			reboot
-			sleep 2
-		# "NO" or timeout choice for Test_Video msgbox thus DIALOG_OK exit code or error -1/255
-		else
-			# Correct variant for bittboy2x_v1 (non forced)
-			echo "CONSOLE_VARIANT=bittboy" > ${MOUNTDIR}/console.cfg
-			sync
-			sleep 0.1
-			reboot
-			sleep 2
-		fi
+			# "YES" choice for Test_Video msgbox DIALOG_EXTRA exit code
+			if test $CHOICE_FIRST -eq 3; then
+				# Correct variant for st7789s (non forced)
+				echo "CONSOLE_VARIANT=st7789s" > ${MOUNTDIR}/console.cfg	
+			# "Flipped!" choice for Test_Video msgbox DIALOG_CANCEL exit code
+			elif test $CHOICE_FIRST -eq 1; then
+				# Correct variant for bittboy3.5 (non forced)
+				echo "CONSOLE_VARIANT=bittboy3" > ${MOUNTDIR}/console.cfg
+				sync
+				sleep 0.1
+				reboot
+				sleep 2
+			# "NO" or timeout choice for Test_Video msgbox thus DIALOG_OK exit code
+			elif test $CHOICE_FIRST -eq 0; then
+				# Correct variant for bittboy2x_v1 (non forced)
+				echo "CONSOLE_VARIANT=bittboy" > ${MOUNTDIR}/console.cfg
+				sync
+				sleep 0.1
+				reboot
+				sleep 2
+			# Error (DIALOG_ERROR) or ESCAPE button pressed (DIALOG_ESCAPE) thus exit code -1/255
+			else
+				dialog --timeout 2 --msgbox "Invalid choice, please redo the test!" 0 0
+				sleep 1.5
+			fi
+		}
+		
+		# Loop Test_Video until correct selection has been performed (CHOICE_FIRST=0/1/3)
+		while true; do
+			test_video_func
+			if ! (test $CHOICE_FIRST -eq -1 || test $CHOICE_FIRST -eq 255); then
+				break
+			fi
+		done
 	elif (grep "DETECTED_VERSION=GC9306/GC9305 controller from gc9306fb" "${MOUNTDIR}/uEnv.txt"); then
 		echo "CONSOLE_VARIANT=m3" > ${MOUNTDIR}/console.cfg
 
@@ -187,13 +201,18 @@ if ! $FOUND_CONSOLE && ! $FOUND_CONSOLE_AUTO; then
 	rm $TEMP
 fi
 
+console_unknown_func(){
+	echo "CONSOLE_VARIANT=unknown" > ${MOUNTDIR}/console.cfg
+	echo "##DO_NOT_REMOVE_THIS_LINE##" >> ${MOUNTDIR}/console.cfg
+}
+
 # Defaulting to console overwriting inactive
 export CONSOLE_OVERWRITE=false
 # test if no device specified in console.cfg
 if ! $FOUND_CONSOLE || $FOUND_CONSOLE_AUTO; then
 	## show selection menu for ST7789S devices
 	if test "$CONSOLE_VARIANT" == "st7789s"; then
-		dialog --clear --title "Select your device:" --menu " " 15 40 5 \
+		dialog --clear --timeout 60 --title "Select your device:" --menu " " 15 40 5 \
 		1 "Powkiddy Q20" \
 		2 "Powkiddy Q90" \
 		3 "Powkiddy V90" \
@@ -202,6 +221,13 @@ if ! $FOUND_CONSOLE || $FOUND_CONSOLE_AUTO; then
 		2> $TEMP
 		## Defaulting to console overwriting active
 		export CONSOLE_OVERWRITE=true
+		
+		## Default CONSOLE_VARIANT for st7789s screns
+		default_console_func(){
+			echo "CONSOLE_VARIANT=pocketgo" > ${MOUNTDIR}/console.cfg
+			# No need to overwrite uboot FORCE version for default so continue procedure
+			export CONSOLE_OVERWRITE=false
+		}
 		## Read the user's choice from the file
 		CHOICE=$(cat $TEMP)
 		## Perform actions based on the user's choice
@@ -220,62 +246,73 @@ if ! $FOUND_CONSOLE || $FOUND_CONSOLE_AUTO; then
 				;;
 			4)
 				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " PocketGo" 5 18
-				echo "CONSOLE_VARIANT=pocketgo" > ${MOUNTDIR}/console.cfg
-				# PocketGo matches default variant, so no need to overwrite uboot FORCE version and continue
-				export CONSOLE_OVERWRITE=false
+				default_console_func
 				;;
 			5)
 				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " PocketGo+TE" 5 18
 				echo "CONSOLE_VARIANT=pocketgo_TE" > ${MOUNTDIR}/console.cfg
 				;;
 			*)
-				echo "Invalid choice. Exiting and selecting default device from autodetection."
-				export CONSOLE_OVERWRITE=false
-				sleep 2
+				dialog --timeout 4 --msgbox "Invalid choice. Exiting and selecting default device from autodetection." 0 0
+				default_console_func
+				sleep 0.1
 				;;
 		esac
 	# Test_Keyboard if proper miyoo.kbd  version was loaded: 
 	elif test "$CONSOLE_VARIANT" == "bittboy3" || test "$CONSOLE_VARIANT" == "bittboy2" || test "$CONSOLE_VARIANT" == "xyc" || test "$CONSOLE_VARIANT" == "m3"; then
-		dialog --defaultno --ok-label YES --cancel-label NO --stdout --title   "  Test Keyboard" \
-		--colors --pause "\n\n  \ZuDoes D-pad works correctly?\Zn\n\nSelect an option & press START" 12 34 10
+		test_keyboard_func(){
+			dialog --ok-label NO --cancel-label YES --stdout --title   "  Test Keyboard" \
+			--colors --pause "\n\n  \ZuDoes D-pad works correctly?\Zn\n\nSelect an option & press START" 12 34 10
 
-		echo $? > $TEMP
-		## Read the user's last choice from the tmp file
-		CHOICE_2=$(cat $TEMP)
+			echo $? > $TEMP
+			## Read the user's last choice from the tmp file
+			CHOICE_2=$(cat $TEMP)
 
-		# "YES" choice for Test_Keyboard msgbox DIALOG_OK exit code
-		## thus we have valid version, just update to FORCE_VERSION and continue
-		if test $CHOICE_2 -eq 0; then
-			if test "$CONSOLE_VARIANT" == "bittboy3"; then
-				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " BittBoy3.5" 5 18
-				echo "CONSOLE_VARIANT=bittboy3.5" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "bittboy2"; then
-				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " BittBoy2x v2" 5 18
-				echo "CONSOLE_VARIANT=bittboy2x_v2" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "xyc"; then
-				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " XYC Q8" 5 18
-				echo "CONSOLE_VARIANT=xyc_gc9306" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "m3"; then
-				dialog --colors --timeout 2 --ok-label " Your device " --msgbox " SUP M3" 5 18
-				echo "CONSOLE_VARIANT=m3_gc9306" > ${MOUNTDIR}/console.cfg
+			# "YES" choice for Test_Keyboard msgbox DIALOG_CANCEL exit code
+			## thus we have valid version, just update to FORCE_VERSION and continue
+			if test $CHOICE_2 -eq 1; then
+				if test "$CONSOLE_VARIANT" == "bittboy3"; then
+					dialog --colors --timeout 2 --ok-label " Your device " --msgbox " BittBoy3.5" 5 18
+					echo "CONSOLE_VARIANT=bittboy3.5" > ${MOUNTDIR}/console.cfg
+				elif test "$CONSOLE_VARIANT" == "bittboy2"; then
+					dialog --colors --timeout 2 --ok-label " Your device " --msgbox " BittBoy2x v2" 5 18
+					echo "CONSOLE_VARIANT=bittboy2x_v2" > ${MOUNTDIR}/console.cfg
+				elif test "$CONSOLE_VARIANT" == "xyc"; then
+					dialog --colors --timeout 2 --ok-label " Your device " --msgbox " XYC Q8" 5 18
+					echo "CONSOLE_VARIANT=xyc_gc9306" > ${MOUNTDIR}/console.cfg
+				elif test "$CONSOLE_VARIANT" == "m3"; then
+					dialog --colors --timeout 2 --ok-label " Your device " --msgbox " SUP M3" 5 18
+					echo "CONSOLE_VARIANT=m3_gc9306" > ${MOUNTDIR}/console.cfg
+				fi
+			# "NO" or timeout choice for Test_Keyboard msgbox DIALOG_OK exit code
+			## thus correct Auto-Detection variant and reboot
+			elif test $CHOICE_2 -eq 0; then
+				if test "$CONSOLE_VARIANT" == "bittboy3"; then
+					echo "CONSOLE_VARIANT=bittboy2x_v2" > ${MOUNTDIR}/console.cfg
+				elif test "$CONSOLE_VARIANT" == "bittboy2"; then
+					console_unknown_func
+				elif test "$CONSOLE_VARIANT" == "xyc"; then
+					console_unknown_func
+				elif test "$CONSOLE_VARIANT" == "m3"; then
+					echo "CONSOLE_VARIANT=xyc" > ${MOUNTDIR}/console.cfg
+				fi
+				sync
+				sleep 0.1
+				reboot
+				sleep 2
+			# Error (DIALOG_ERROR) or ESCAPE button pressed (DIALOG_ESCAPE) thus exit code -1/255
+			else
+				dialog --timeout 2 --msgbox "Invalid choice, please redo the test!" 0 0
+				sleep 1.5
 			fi
-		# "NO" choice for Test_Keyboard msgbox DIALOG_CANCEL exit code and -1/255
-		## thus correct Auto-Detection variant and reboot
-		else
-			if test "$CONSOLE_VARIANT" == "bittboy3"; then
-				echo "CONSOLE_VARIANT=bittboy2x_v2" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "bittboy2"; then
-				echo "CONSOLE_VARIANT=bittboy3.5" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "xyc"; then
-				echo "CONSOLE_VARIANT=m3" > ${MOUNTDIR}/console.cfg
-			elif test "$CONSOLE_VARIANT" == "m3"; then
-				echo "CONSOLE_VARIANT=xyc" > ${MOUNTDIR}/console.cfg
+		}
+		# Loop Test_Keyboard until correct selection has been performed (CHOICE_FIRST=0/1/3)
+		while true; do
+			test_keyboard_func
+			if ! (test $CHOICE_2 -eq -1 || test $CHOICE_2 -eq 255); then
+				break
 			fi
-			sync
-			sleep 0.1
-			reboot
-			sleep 2
-		fi
+		done
 	elif test "$CONSOLE_VARIANT" == "bittboy"; then
 		dialog --colors --timeout 2 --ok-label " Your device " --msgbox " BittBoy2x v1" 5 18
 		echo "CONSOLE_VARIANT=bittboy2x_v1" > ${MOUNTDIR}/console.cfg
@@ -327,21 +364,19 @@ if $FOUND_CONSOLE; then
 				dialog --colors --timeout 2 --ok-label " Your device " --msgbox "      SUP M3\n(GC9306 controller)" 6 24
 				;;
 		*)
-				dialog --colors --timeout 2 --ok-label " Your device " --msgbox "\Zb\Z1 Unknown\Zn" 5 18
-				echo "CONSOLE_VARIANT=unknown" > ${MOUNTDIR}/console.cfg
-				echo "##DO_NOT_REMOVE_THIS_LINE##" >> ${MOUNTDIR}/console.cfg
-				;;
+				dialog --colors --timeout 2 --ok-label " Your device " --msgbox "\Zb\Z1 Unknown-Error\Zn" 5 18
 	esac
+elif ! $FOUND_CONSOLE; then
+	dialog --colors --timeout 2 --ok-label " Your device " --msgbox "\Zb\Z1 Unknown\Zn" 5 18
+	console_unknown_func
 fi
 
 #License prompt
-if (dialog --clear --ok-label NO --cancel-label YES --stdout --title "   License agreement" \
-	--colors --pause "\n              \ZbMiyooCFW\Zn\n$LICENSE" 22 60 30); then
+if (!(dialog --clear --defaultno --ok-label YES --cancel-label NO --stdout --title "   License agreement" \
+	--colors --pause "\n              \ZbMiyooCFW\Zn\n$LICENSE" 22 60 30) || (test $? -eq 255)); then
 	echo -en "     We understand. Have a nice day!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
 	sleep 1
-	echo "CONSOLE_VARIANT=unknown" > ${MOUNTDIR}/console.cfg
-	echo "##DO_NOT_REMOVE_THIS_LINE##" >> ${MOUNTDIR}/console.cfg
-	dialog --colors --timeout 2 --ok-label " Your device " --msgbox "\Zb\Z1 Unknown\Zn" 5 18
+	console_unknown_func
 	sync
 	sleep 0.1
 	poweroff
