add logs for parted cmd in p5 resize
also output LICENSE sign info

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -152,18 +152,14 @@ safe_reboot_func(){
 	SHUTDOWN=reboot
 	safe_shutdown_func
 	reboot
-	while (pgrep "reboot"); do
-		sleep 1
-	done
+	sleep 10000
 }
 
 safe_poweroff_func(){
 	SHUTDOWN=poweroff
 	safe_shutdown_func
 	poweroff
-	while (pgrep "poweroff"); do
-		sleep 1
-	done
+	sleep 10000
 }
 
 console_unknown_func(){
@@ -536,9 +532,12 @@ echo "License agreement signing" >> ${LOG}
 if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --ok-label NO --cancel-label YES --stdout --title "   License agreement" \
 	--colors --pause "\n              \ZbMiyooCFW\Zn\n$LICENSE" 22 60 30 || test $? -eq 255); then
 	echo -en "     We understand. Have a nice day!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | tee -a ${LOG}
+	echo "License not signed, exiting..." >> ${LOG}
 	sleep 1
 	console_unknown_func
 	safe_poweroff_func
+else
+	echo "License signed, continuing..." >> ${LOG}
 fi
 
 # Format swap parition
@@ -605,7 +604,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label "$
 else
 	P4_FS_TYPE="${P4_FS_TYPE_EXTRA}"
 	echo -en "\n\nConverting the ${P4_LABEL} partition filesystem to ${P4_FS_TYPE} type.\n\n" | tee -a ${LOG}
-	echo -en "\e[32mThis can take a few minutes, be patient!\e[0m"
+	echo -en "\e[32mThis can take a few minutes, be patient!\e[0m\n"
 	sleep 3
 	mkdir "${ROMS}"/backup 2>&1 | tee -a ${LOG}
 	if test "${P5_FS_TYPE}" == "VFAT"; then
@@ -694,7 +693,7 @@ else
 fi
 if $CHANGE_FS_P5; then
 	echo -en "\n\nConverting the ${P5_LABEL} partition filesystem to ${P5_FS_TYPE} type.\n\n" | tee -a ${LOG}
-	echo -en "\e[32mThis can take a few minutes, be patient!\e[0m"
+	echo -en "\e[32mThis can take a few minutes, be patient!\e[0m\n"
 	sleep 3
 	mkdir "${HOME}"/backup 2>&1 | tee -a ${LOG}
 	rsync -a --info=nonreg0 --info=progress2 "${ROMS}" "${HOME}"/backup
@@ -769,6 +768,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 	clear
 	SD_MAX_AVAIL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} / 1024 / 1024" | bc) #only to inform user about end point for resize
 	SD_MAX_AVAIL_SIZE_IN_GB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} * 1024 / 1000 / 1000 / 1000" | bc)
+	SD_MAX_AVAIL_SIZE_IN_MB=$((SD_MAX_AVAIL_SIZE_IN_KiB * 1024 / 1000 / 1000))
 	P5_SIZE_IN_GB=$(echo "scale=1; ${P5_SIZE} * 512 / 1000 / 1000 / 1000" | bc)
 	# roundup GB value to 0,1GB for integer calculations:
 	SD_MAX_AVAIL_SIZE_IN_GBx10=$(echo "$SD_MAX_AVAIL_SIZE_IN_GB" | tr -d ".")
@@ -809,7 +809,7 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 		echo "Resizing the ${P5_LABEL} (${P5_FS_TYPE}) partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
 		umount /dev/mmcblk0p5 2>&1 | tee -a ${LOG}
 		if test "${P5_FS_TYPE}" == "VFAT"; then
-			echo -en "\e[32mThis can take a few minutes, be patient!\e[0m"
+			echo -en "\e[32mThis can take a few minutes, be patient!\e[0m\n"
 			#TODO: fix outputting logs from fatresize stdout
 			fatresize --size="${SD_MAX_AVAIL_SIZE_IN_KiB}"ki -v -p /dev/mmcblk0p5 -n5 2>&1 | tee -a ${LOG}
 			fsck.fat -y /dev/mmcblk0p5 2>&1 | tee -a ${LOG}
@@ -817,8 +817,10 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 			sync
 			mount -t vfat -o rw,utf8 /dev/mmcblk0p5 "${ROMS}" 2>&1 | tee -a ${LOG}
 		else
-			echo -en "\e[32mThis can take a few seconds!\e[0m"
-			P5_START_POINT=` parted --script /dev/mmcblk0 unit MB print | grep '5' | tail -n1 | awk '{print $2}'`
+			echo -en "\e[32mThis can take a few seconds!\e[0m\n"
+			P5_START_POINT=$(parted --script /dev/mmcblk0 unit MB print 2>&1 | tee -a ${LOG} | grep '5' | tail -n1 | awk '{print $2}') \
+			 && echo -en "Expanding 5'th partition from START sector ${P5_START_POINT} to END \n in total size: ${SD_MAX_AVAIL_SIZE_IN_MB}MB\n" | tee -a ${LOG} \
+			 || echo -en "ERROR: Failed to determine P5_START_POINT for resizing" | tee -a ${LOG}
 			parted -a optimal /dev/mmcblk0 --script rm '5'  2>&1 | tee -a ${LOG}
 			parted -a optimal /dev/mmcblk0 --script mkpart roms $P5_START_POINT 100%  2>&1 | tee -a ${LOG}
 			partx -u /dev/mmcblk0 2>&1 | tee -a ${LOG}
