list UDC after umtprd + other fixes
mostly logs & default mode (no args)

diff --git a/board/miyoo/rootfs/usr/bin/usb-mode b/board/miyoo/rootfs/usr/bin/usb-mode
--- a/board/miyoo/rootfs/usr/bin/usb-mode
+++ b/board/miyoo/rootfs/usr/bin/usb-mode
@@ -5,8 +5,10 @@ USB_MODE="${1}"
 MTP_APP="${2}"
 
 # Global variables
-SYSDIR=/sys/kernel/config/usb_gadget/
+SYSDIR=/sys/kernel/config/usb_gadget
 DEVDIR=$SYSDIR/g2
+MAC_HOST="12:34:56:78:9a:bd"
+MAC_DEV="12:34:56:78:9a:bc"
 
 st_error_func(){
 	st -k -e "/bin/sh" "-c" "echo -e \"\e[31m${1}\e[0m\"; sleep 2"
@@ -19,10 +21,18 @@ st_exec_func(){
 }
 
 rm_gadget_func(){
-	killall umtprd umtprd-debug
+	echo "Removing old gadgets"
+	if pgrep "umtprd"; then
+		killall umtprd
+	elif pgrep "umtprd-debug"; then
+		killall umtprd-debug
+	fi
 	gadget-vid-pid-remove 0x1d6b:0x0104 # simply rm gadget-hid (g_hid/g_multi?) as it isn't part of FunctionFS 
 
-	[ -d $DEVDIR ] || exit
+	if ! test -d $DEVDIR; then
+		echo "ERROR: couldn't find ${DEVDIR}"
+		return
+	fi
 
 	echo '' > $DEVDIR/UDC
 
@@ -56,6 +66,7 @@ rm_gadget_func(){
 }
 
 rm_host_modules_func(){
+	echo "Removing USB HOST mode's all modules" 
 	modprobe -r evdev
 	modprobe -r joydev
 	modprobe -r analog
@@ -71,29 +82,42 @@ rm_host_modules_func(){
 }
 
 usb_mode_func(){
+	test -z "${1}" \
+	 || echo "Suggesting USB mode in ../musb-hdrc.1.auto/mode"
 	_usb_mode_path_="/sys/devices/platform/soc/1c13000.usb/musb-hdrc.1.auto/mode"
 	_usb_mode_="$(cat ${_usb_mode_path_})"
-	test "${_usb_mode_}" == "host" \
-	 && rm_host_modules_func
-	echo ${1} > ${_usb_mode_path_}
+	echo "Current USB mode=${_usb_mode_}"
+	if (grep -q host "${_usb_mode_path_}" && ! test -z "${1}"); then
+		rm_host_modules_func
+	fi
+	test -z "${1}" \
+	 || echo "${1}" > ${_usb_mode_path_} # DOES THIS EVEN WORK?
+	sleep 1
+	# _usb_mode_="$(cat ${_usb_mode_path_})"
+	# echo "NEW usb_mode=${_usb_mode_}"
 }
 
 usb_configs_func(){
+	echo "Configuring FunctionFS gadget"
 	mount none /sys/kernel/config -t configfs
 	mkdir -p ${DEVDIR}
-	cd ${DEVDIR} || echo "ERROR: couldn't enter ${DEVDIR}" && exit 1
+	if ! cd ${DEVDIR}; then
+		echo "ERROR: couldn't enter ${DEVDIR}"
+		exit 1
+	fi
 	mkdir -p configs/c.1
-	if test "${USB_MODE}" == "mtp"; then
+	if test "${USB_MODE}" == "mtp" || test -z $USB_MODE; then
 		mkdir -p functions/ffs.mtp # mtp
 	elif test "${USB_MODE}" == "serial"; then
 		mkdir -p functions/acm.usb0 # serial
+	# else net
 	fi
 	mkdir -p strings/0x409
 	mkdir -p configs/c.1/strings/0x409
 	if test "${USB_MODE}" == "net"; then
 		mkdir -p functions/rndis.usb0
 	fi
-	if test "${USB_MODE}" == "mtp"; then
+	if test "${USB_MODE}" == "mtp" || test -z $USB_MODE; then
 		echo 0x0100 > idProduct # mtp gadget (ptp's extension)
 	else
 		echo 0x0104 > idProduct # serial,net (g_multi?), CDC ACM
@@ -120,7 +144,7 @@ usb_configs_func(){
 
 	echo "Conf 1" > configs/c.1/strings/0x409/configuration
 	echo 120 > configs/c.1/MaxPower
-	if test "${USB_MODE}" == "mtp"; then
+	if test "${USB_MODE}" == "mtp" || test -z $USB_MODE; then
 		# mtp
 		ln -s functions/ffs.mtp configs/c.1
 		mkdir -p /dev/ffs-mtp
@@ -128,26 +152,32 @@ usb_configs_func(){
 	elif test "${USB_MODE}" == "serial"; then
 		# serial
 		ln -s functions/acm.usb0 configs/c.1
-	else
+	elif test "${USB_MODE}" == "net"; then
 		# net
 		ln -s functions/rndis.usb0 configs/c.1
 		ln -s configs/c.1 os_desc
 		sleep 1
 
 		echo "0x00" > bDeviceClass
+	else
+		echo "ERROR: Unknown USB_MODE=${USB_MODE}"
 	fi
-
-	sleep 1
-	ls /sys/class/udc/ > ${DEVDIR}/UDC
 }
 
 ### MTP/MTD (default)###
 if test "${USB_MODE}" == "mtp" || test -z $USB_MODE; then
-	usb_mode_func peripheral
+	echo "Starting USB-MTP mode"
+	test -z $USB_MODE \
+	 || usb_mode_func peripheral
 	modprobe usb_f_fs
-	rm_gadget_func
+	if ! test -z $USB_MODE; then
+	# omit removing gadgets in default non-arg run
+		rm_gadget_func
+	fi
+
 	usb_configs_func
 	if test "${MTP_APP}" == "umtprd"; then
+		echo "Launching uMTP-Responder app"
 		if (grep -q DEBUG_UMTPR\=\1 "${HOME}/options.cfg"); then
 			umtprd-debug &
 		else
@@ -155,10 +185,15 @@ if test "${USB_MODE}" == "mtp" || test -z $USB_MODE; then
 		fi
 	fi
 	sleep 1
+	ls /sys/class/udc/ > ${DEVDIR}/UDC
+	
+	usb_mode_func
+	sleep 1
 fi
 
 ### HID ###
 if test "${USB_MODE}" == "hid"; then
+	echo "Starting USB-HID mode"
 	usb_mode_func peripheral
 	rm_gadget_func
 	modprobe usb_f_hid
@@ -166,6 +201,7 @@ if test "${USB_MODE}" == "hid"; then
 	modprobe uinput
 	mount none /sys/kernel/config -t configfs
 	gadget-hid
+	usb_mode_func
 	st_exec_func "\
 		echo -e \"\e[32m\n\n\n\n\n\n               Starting USB-HID mode\e[0m\n\n\n\"; \
 		sleep 1; \
@@ -177,14 +213,24 @@ fi
 
 ### Serial Console ###
 if test "${USB_MODE}" == "serial"; then
+	echo "Starting USB-Serial mode"
 	usb_mode_func peripheral
 	rm_gadget_func
 	usb_configs_func
+	sleep 1
+	ls /sys/class/udc/ > ${DEVDIR}/UDC
+	usb_mode_func
 fi
 
 ### Networking ###
 if test "${USB_MODE}" == "net"; then
+	st_info_func "Starting USB-Network mode"
+	rm_gadget_func
+	modprobe usb_f_rndis
+	sleep 1
 	usb_configs_func
+	sleep 1
+	ls /sys/class/udc/ > ${DEVDIR}/UDC
 	ifconfig usb0 up 192.168.137.1
 	sleep 10
 	/etc/init.d/S80dhcp-server restart
@@ -192,6 +238,7 @@ fi
 
 ### Host ##
 if test "${USB_MODE}" == "host"; then
+	echo "Starting USB in HOST state mode"
 	usb_mode_func host
 	sleep 2
 
@@ -207,4 +254,7 @@ if test "${USB_MODE}" == "host"; then
 	modprobe usbhid
 	modprobe hid-generic
 	modprobe hid
+	usb_mode_func
 fi
+
+echo "Exiting USB mode configuration..."
